SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 720

GRID_COLS = 40
GRID_ROWS = 24

TILE_SIZE = SCREEN_WIDTH // GRID_COLS

PLAYER_WIDTH = int(TILE_SIZE)
PLAYER_HEIGHT = int(TILE_SIZE * 1.2)
LINE_WIDTH = 3
GRAVITY = 980
SPIKE_SIZE = 20
LAVA_HEIGHT_RATIO = 0.75