SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 720

GRID_COLS = 20
GRID_ROWS = 12

TILE_SIZE = SCREEN_WIDTH // GRID_COLS

PLAYER_WIDTH = int(TILE_SIZE * 0.9)
PLAYER_HEIGHT = int(TILE_SIZE * 1.25)
LINE_WIDTH = 3
GRAVITY = 980
SPIKE_SIZE = 19

PLAYER_MAX_HEALTH = 5