OPENING_CARDS = [
    "BOX JUMP", 
    "Original Game by Aoife Bee", 
    "Artwork by Aoife Bee", 
    "DO NOT STEAL"
]

END_CREDITS = [
            ("title", "BOX JUMP"),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("title", "A game by Aoife Bee"),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("heading", "Art and Design"),
            ("name", "Aoife Bee"),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("heading", "Level Design"),
            ("name", "Aoife Bee"),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("heading", "Creative Visionary"),
            ("name", "Aoife Bee"),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("heading", "Programming"),
            ("name", "Aoife Bee"),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("heading", "Best Girl"),
            ("name", "Aoife Bee"),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("heading", "Special Thanks"),
            ("name", "Twitch Chat"),
            ("name", "Giraffeguin"),
            ("name", "Aoife Bee"),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("title", "THANKS FOR PLAYING!"),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("spacer", ""),
            ("title", "ORIGINAL GAME DO NOT STEAL !")

        ]