ROOM_01_MAP = [
    "                                                .",
    "                                                .",
    "                                                .",
    "                                                .",
    "                                                .",
    "                                                .",
    "                                               gg",
    "                                             gggg",
    "                                           gggggg",
    "                                       gggggggggg",
    "                                  ggggggggggggggg",
    "                            ggggggggggggggggggggg",
    "                                         ggggggtt",
    "                    bb                      gggtt",
    "    bb                                        gtt",
    "                                               tt",                
    "               bb                              tt",              
    "                                               tt",
    "                               bbb        g    tt",
    "                     bbb                 gggg  tt",
    "                                        gtttttttt",
    "                                         ggg   tt",
    "                                    bb         tt",
    "                                               tt",
    "                 g                             tt",
    "                 gg           bbb              tt",         
    "                 t     bbb                     tt",              
    "          bbb    t                             tt",             
    "                 t                             tt",                 
    "   P            ttt                            tt",                   
    "ggggggggggggggggggggggggggggggggggggggggggggggggg",

]

ROOM_02_MAP = [
    "t                                                                              ",
    "t        ^^                                                                    ",
    "        <tt>                                                                   ",
    "         vv                                                                    ",
    "                                                                               ",
    " P  ^^^                                                                        ",
    "ggggttt>                                                                       ",
    "ggggttgggg                                                                     ",
    "gggttggggggg                                                                   ",
    "ggttggggggggg       ggg                                                        ",
    "gttggggggggt        gggg                                                       ",
    "ttggggggggtt         ttgg                                                      ",
    "tgg    gggtt^^^^^^^^^ttg    bb                 ^^^^                            ",
    "t       ggttttttttttttt                   ^   <tttt>                          #",
    "t        ggggggggggggtt          bb      <t>   vvvv                           #",
    "t                ggggtt               ggggt>                                 ##",
    "t                  ggtt                gtttgg          ^^                  ####",
    "t                   gtt                 ttgg          <tt>               ######",
    "t                    tt                 tt      gggg  <tt>                #####",
    "t                    tt                 tt      gttg   vv                   ###",
    "t                    tt                 tt       tgg                        ###",
    "t                    tt                 tt       t                  ^^     ####",
    "t                    tt                 tt       t        #########<##>   #####",
    "                     tt                 tt       t        #####     vv     ####",
    "                     tt                 tt       t       #####              ###",
    "                     tt                 tt       t       ####     #         ###",
    "                     tt                 tt       t      #####     ####^^^   ###",
    "                     tt                 tt       t      #####     #############",
    "                     tt                 tt       t       #####               ##",
    "                     tt                 tt       t        #####               #",
    "                     tt                 tt       t         ######             #",
    "                     tt                 tt       t          #######           #",
    "                     tt                 tt       t           ##############   #",

]

ROOM_03_MAP = [
    "#...#                                   #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   #                                #",
    "#   ###                                #",
    "#                                      ",
    "#========#                                   #",
    "####################################",

]

ROOMS = { 
    "room_01": {
        "layout": ROOM_01_MAP,
        "sky_top": (90, 160, 255),
        "sky_bottom": (180, 220, 255),
    },
    "room_02": {
       "layout": ROOM_02_MAP,
        "sky_top": (255, 140, 80),
        "sky_bottom": (120, 70, 160), 
    },
    "room_03": {
        "layout": ROOM_03_MAP,
        "sky_top": (0, 20, 0),
        "sky_bottom": (5, 40, 5),
    },
}

START_ROOM = "room_02"

DOORS = {
    "room_01": [
        {"id": "right_exit", 
        "rect": (49, 0, 1, 6), 
        "edge": "right", 
        "to": ("room_02", "left_exit")},
    ],
    "room_02": [
        {"id": "left_exit", 
        "rect": (-1, 2, 1, 4), 
        "edge": "left",
        "to": ("room_01", "right_exit")},

        {"id": "down_exit",  
        "rect": (75, 34, 3, 1), 
        "edge": "down",
        "to": ("room_03", "up_exit")},
    ],
    "room_03": [
        {"id": "up_exit", 
        "rect": (1, -1, 3, 1), 
        "edge": "up",
        "to": ("room_02", "down_exit")},
    ],
}