ROOM_01_MAP = [
    "                                                .",
    "                                                .",
    "                                                .",
    "                                                .",
    "                                                .",
    "                                                .",
    "                                               gg",
    "                                             gggg",
    "                                           gggggg",
    "                                       gggggggggg",
    "                                  ggggggggggggggg",
    "                            ggggggggggggggggggggg",
    "                                         ggggggtt",
    "                    cc                      gggtt",
    "    cc                                        gtt",
    "                                               tt",                
    "               cc                              tt",              
    "                                               tt",
    "                               ccc        g    tt",
    "                     ccc                 gggg  tt",
    "                                        gtttttttt",
    "                                         ggg   tt",
    "                                    cc         tt",
    "                                               tt",
    "                 g                             tt",
    "                 gg           ccc              tt",         
    "                 t     ccc                     tt",              
    "          ccc    t                             tt",             
    "                 t                             tt",                 
    "   P            ttt                            tt",                   
    "ggggggggggggggggggggggggggggggggggggggggggggggggg",

]

ROOM_02_MAP = [
    "t                                                                              ",
    "t        ^^                                                                    ",
    "        <tt>                                                                   ",
    "         vv                                                                    ",
    "                                                                               ",
    "    ^^^                                                                        ",
    "ggggttt>                                                                       ",
    "ggggttgggg                                                                     ",
    "gggttggggggg                                                                   ",
    "ggttggggggggg       ggg                                                        ",
    "gttggggggggt        gggg                                                       ",
    "ttggggggggtt         ttgg                                                      ",
    "tgg    gggtt^^^^^^^^^ttg    cc                 ^^^^                            ",
    "t       ggttttttttttttt                   ^   <tttt>                          #",
    "t        ggggggggggggtt          cc      <t>   vvvv                           #",
    "t                ggggtt               ggggt>                                 ##",
    "t                  ggtt                gtttgg          ^^                  ####",
    "t                   gtt                 ttgg          <tt>               ######",
    "t                    tt                 tt      gggg  <tt>                #####",
    "t                    tt                 tt      gttg   vv                   ###",
    "t                    tt                 tt       tgg                        ###",
    "t                    tt                 tt       t                  ^^     ####",
    "t                    tt                 tt       t        #########<##>   #####",
    "                     tt                 tt       t        #####     vv     ####",
    "                     tt                 tt       t       #####              ###",
    "                     tt                 tt       t       ####     #         ###",
    "                     tt                 tt       t      #####     ####^^^   ###",
    "                     tt                 tt       t      #####     #############",
    "                     tt                 tt       t       #####               ##",
    "                     tt                 tt       t        #####               #",
    "                     tt                 tt       t         ######             #",
    "                     tt                 tt       t          #######           #",
    "                     tt                 tt       t           ##############   #",

]

ROOM_03_MAP = [
    "#   ########################ss~#########################################################################",
    "#   #######                   ~ #################################################################      .",
    "#   ####                      ~  ###########################################m                 ###      .",
    "#   ####                      ~                         #######                                #       .",
    "#   ####                      ~                          #####                                         .",
    "#   ####                      ~                           ###                                        ###",
    "#   ####                      ~                            #                                       #####",
    "#   ####                      ~                                                      =========sss#######",
    "#   ##                        ~                                             ##       ~ssssssssss########",
    "#   #                         ~                                                      ~~sssssssss########",
    "#   #                         ~                ###                                   ~~ ssssssss########",
    "#   #            #            ~             ########                   bb            ~~  ssssss#########",
    "#   ##           #            ~             ##s#######               bbbb            ~~   sssss#########",
    "#   ###        ###          ==~             sss#########           bbbbb             ~~      ss#########",
    "#   ###          #        #sss~             ssv#########         bbbbbbb             ~~      ss#########",
    "#   ##          =s         ##s~  ##         s    ########        bbbbbb       ###    ~~      ss#########",
    "#   #          #ss            ~  vv         s     #######       bbbbbbb              ~~      ss#########",
    "#   #           ##            ~     ##      ~      #####s     bbbbbbbb              =~~      s##########",
    "#   ##          ##            ~     vv      ~      #####s    bbbbbbbbb              ~b~      s##########",
    "#   ##           #           =~            =~=    #####ss# bbbbbbbbb               bbb~=      s##########",
    "#   ###          #           ~~        ####sss#  #####sss###bbbbbbb               bbbbb~      s#########",
    "#   ###    ==s   #           ~~       ####sss#    #####ss####bbbbbb               bbbbb~     s##########",
    "#   ##    ssss   #           ~~       ####ss###    ###ss#####bbbbb                bbbbb~=     s##########",
    "#   ##           #           ~~       #####s####    ##ss######bbb                bbbbbbb~    s##########",
    "#   #            #          =~~       ###ss######   sss########b                 bbbbbbb~    s##########",
    "#   #            #          ~~~       ###s~       ==~s##########                 bbbbbbb~=     s########",
    "#   ##           #          ~s~        ##s~=   ###sssss###v#######              bbbbbbbbb~     s########",
    "#   ###          #          ~v~        ##ss~=s  ##s###s##v v#######             bbbbbbbbb~     s########",
    "#   #            s          ~ ~        ####ssss  #ss##       <#####             bbbbbbbbb~=    s########",
    "#   #         ==ss          ~ ~        ########  v~v   ####  <#####            bbbbbbbbbbb~    s########",
    "#   #         ~sss          ~ ~        ########s==~= s###### <####             bbbbbbbbbbb~    s########",
    "~~  s         ~  #          ~ ~         #######sssssss#####  ####              bbbbbbbbbbb~======s######",
    "s~  s==       ~             ~ ~         ########ss>~         ###              bbbbbbbbbbbbb~~~~~~s######",
    "s~  sss#     =~==           ~ ~          ######### ~ ###########              bbbbbbbbbbbbb~~~~~~s######",
    "s~  ss      =~ss~           ~ ~           ####s====~===============           bbbbbbbbbbbbb~~~~~~s######",
    "s~=========sssss~           ~ ~           ####sssssssssssssssssssss#        bbbbbbbbbbbbbbb~~~~~~s######",
    "ssssssssssss#sss~           ~ ~          #########ssssssssssss#############################~~~~~~s######",

] 

ROOM_04_MAP = [
    "g                        g",
    "g                        g",
    "g                        g",
    "g                        g",
    "g           *            g",
    "g          ccc           g",
    "g                        g",
    ".                        g",
    ".      ccc     ccc       g",
    ".                        g",
    ".                        g",
    "gggggggggggggggggggggggggg",
]

ROOMS = { 
    "room_01": {
        "layout": ROOM_01_MAP,
        "sky_top": (90, 160, 255),
        "sky_bottom": (180, 220, 255),
    },
    "room_02": {
       "layout": ROOM_02_MAP,
        "sky_top": (255, 140, 80),
        "sky_bottom": (120, 70, 160), 
    },
    "room_03": {
        "layout": ROOM_03_MAP,
        "sky_top": (0, 10, 0),
        "sky_bottom": (5, 30, 5),
    },
    "room_04": {
        "layout": ROOM_04_MAP,
        "sky_top": (255,255,255),
        "sky_bottom": (90, 160, 255),
    }
}

START_ROOM = "room_01"

DOORS = {
    "room_01": [
        {"id": "right_exit", 
        "rect": (49, 0, 1, 6), 
        "edge": "right", 
        "to": ("room_02", "left_exit")},
    ],
    "room_02": [
        {"id": "left_exit", 
        "rect": (-1, 2, 1, 4), 
        "edge": "left",
        "to": ("room_01", "right_exit")},

        {"id": "down_exit",  
        "rect": (75, 34, 3, 1), 
        "edge": "down",
        "to": ("room_03", "up_exit")},
    ],
    "room_03": [
        {"id": "up_exit", 
        "rect": (1, -1, 3, 1), 
        "edge": "up",
        "to": ("room_02", "down_exit")},

        {"id": "right_exit",
         "rect": (104, 0, 1, 5),
         "edge": "right",
         "to": ("room_04", "left_exit")}
    ],
    "room_04": [
        {"id": "left_exit",
         "rect": (-1, 7, 1, 4),
         "edge": "left",
         "to": ("room_03", "right_exit")}
    ]
}